/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lEHbmIThscb
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  CardTitle,
  CardHeader,
  CardDescription,
  CardContent,
  Card,
} from "@/components/ui/card";
import { OfferCarousel } from "./offer-carousel";
import { EmailCta } from "./email-cta";

export function Home() {
  return (
    <div key="1">
      <header className="bg-ai-cubes dark:bg-gray-800 bg-cover bg-center bg-no-repeat relative">
        <div id="Board"></div>
        <div className="max-w-7xl mx-auto py-24 px-4 text-center">
          <div className="backdrop-blur min-w-fit bg-black bg-opacity-25 box-content rounded-lg">
            <h1 className="text-5xl font-bold text-emerald-200 mb-4 antialiased">
              Welcome to RAGnexus
            </h1>
            <div className="text-xl text-gray-900">
              Empowering your business with cutting-edge AI solutions
            </div>
          </div>
          <Link href="#offer">
            <Button className="mt-8">Learn More</Button>
          </Link>
        </div>
      </header>
      <section className="py-16 dark:bg-gray-700" id="offer">
        <div className="max-w-7xl mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Custom AI Solutions
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Build bespoke AI systems tailored to your unique needs.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Personalized Responses
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Highly personalized and contextually relevant responses to your
                individual needs.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Efficiency & Productivity
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Greater efficiency and productivity by obtaining accurate
                information quickly and conveniently.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Customer Experience
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Improvement in customer experience by providing personalized and
                adapted solutions.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Cost Reduction
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Reduced costs by automating repetitive tasks and improving
                data-driven decision making.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Cutting-Edge Technology
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Access to cutting-edge technology and artificial intelligence
                capabilities without the need to internally develop the
                corresponding infrastructure.
              </CardDescription>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="py-8 px-4 bg-gray-100 dark:bg-gray-800" id="about">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-gray-900 dark:text-gray-300 mb-6">
            About RAGnexus
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="text-justify text-lg text-gray-500 dark:text-gray-400">
              <p>
                RAGnexus is a company specialized in creating personalized
                personal assistants using RAG (Retriever-Augmented Generation)
                technology.
              </p>
              <br />
              <p>
                Our assistants are designed to provide highly personalized and
                contextually relevant responses to our clients&apos; individual
                needs. We use private information provided by customers to
                ensure that responses are accurate and tailored to each specific
                use case.
              </p>
            </div>
            <div className="md:ml-8 justify-center flex">
              <OfferCarousel />
            </div>
          </div>
        </div>
      </section>
      <EmailCta />
    </div>
  );
}
