/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lEHbmIThscb
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  CardTitle,
  CardHeader,
  CardDescription,
  CardContent,
  Card,
} from "@/components/ui/card";
import {
  CarouselItem,
  CarouselContent,
  CarouselPrevious,
  CarouselNext,
  Carousel,
} from "@/components/ui/carousel";
import { Input } from "@/components/ui/input";
import { NavBar } from "./nav";

export function Home() {
  return (
    <div
      key="1"
      className="min-h-screen bg-white text-gray-700 font-sans"
      style={{
        fontFamily: "Open Sans, Noto sans-serif",
      }}
    >
      <NavBar />
      <header
        className="bg-[#F3F4F6]"
        style={{
          backgroundColor: "#036f11",
        }}
      >
        <div className="max-w-7xl mx-auto py-24 px-4 text-center">
          <h1
            className="text-5xl font-bold text-gray-800 mb-4"
            style={{
              color: "#ffffff",
            }}
          >
            Welcome to RAGnexus
          </h1>
          <div className="text-xl text-gray-900">
            Empowering your business with cutting-edge AI solutions
          </div>
          <Button>Learn More</Button>
        </div>
      </header>
      <section
        className="py-16"
        style={{
          backgroundColor: "#ffffff",
        }}
      >
        <div className="max-w-7xl mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Custom AI Solutions
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Build bespoke AI systems tailored to your unique needs.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Personalized Responses
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Highly personalized and contextually relevant responses to your
                individual needs.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Efficiency & Productivity
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Greater efficiency and productivity by obtaining accurate
                information quickly and conveniently.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Customer Experience
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Improvement in customer experience by providing personalized and
                adapted solutions.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Cost Reduction
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Reduced costs by automating repetitive tasks and improving
                data-driven decision making.
              </CardDescription>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle
                style={{
                  color: "#04a118",
                }}
              >
                Cutting-Edge Technology
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Access to cutting-edge technology and artificial intelligence
                capabilities without the need to internally develop the
                corresponding infrastructure.
              </CardDescription>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="py-8 px-4 bg-gray-100 dark:bg-gray-800">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-300 mb-6">
            About RAGnexus
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              RAGnexus is a company specialized in creating personalized
              personal assistants using RAG (Retriever-Augmented Generation)
              technology. Our assistants are designed to provide highly
              personalized and contextually relevant responses to our clients'
              individual needs. We use private information provided by customers
              to ensure that responses are accurate and tailored to each
              specific use case.
            </div>
            <div>
              <Carousel className="w-full max-w-xs">
                <CarouselContent>
                  <CarouselItem>
                    <div className="p-1">
                      <Card>
                        <CardContent className="flex aspect-square items-center justify-center p-6 ml-auto">
                          <span className="text-4xl font-semibold">1</span>
                        </CardContent>
                      </Card>
                    </div>
                  </CarouselItem>
                  <CarouselItem>
                    <div className="p-1">
                      <Card>
                        <CardContent className="flex aspect-square items-center justify-center p-6">
                          <span className="text-4xl font-semibold">2</span>
                        </CardContent>
                      </Card>
                    </div>
                  </CarouselItem>
                  <CarouselItem>
                    <div className="p-1">
                      <Card>
                        <CardContent className="flex aspect-square items-center justify-center p-6">
                          <span className="text-4xl font-semibold">3</span>
                        </CardContent>
                      </Card>
                    </div>
                  </CarouselItem>
                </CarouselContent>
                <CarouselPrevious />
                <CarouselNext />
              </Carousel>
            </div>
          </div>
        </div>
      </section>
      <section className="py-8 px-4 bg-gray-100 dark:bg-gray-800">
        <div
          className="max-w-7xl mx-auto"
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "1rem",
          }}
        >
          <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-300 mb-6">
            Discover the Power of AI
          </h2>
          <div className="flex flex-col items-center gap-4 md:flex-row md:items-start md:justify-center">
            <Input
              className="w-full md:w-1/2"
              placeholder="Enter your email"
              type="email"
            />
            <Button className="w-full md:w-auto">Keep me updated</Button>
            <div className="text-gray-700 dark:text-gray-400 text-lg text-center md:text-left">
              Reach out to us today to explore how AI can transform your
              business.
            </div>
            <Link
              className="text-green-light font-medium hover:underline dark:text-green-light"
              href="#"
            >
              Learn more about our AI solutions
            </Link>
          </div>
        </div>
      </section>
      <footer
        className="bg-white border-t py-6"
        style={{
          backgroundColor: "#ffffff",
          borderColor: "#59A52C",
        }}
      >
        <div className="max-w-7xl mx-auto px-4 text-center">
          <span className="text-sm text-gray-500">
            © 2024 RAGnexus. All rights reserved.
          </span>
        </div>
      </footer>
    </div>
  );
}
